# $Copyright (c) 2015 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.$
# Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG
#

#dynamicChainManagers:
#   MQTTManager:
#    transport: UMTransport
#     managerConfig:
#       rnames: ${RNAMEMQTT}
#       channel:
#         prefix: "state:"
        
startChains:
   MQTTreliableTransportChain:
      - apama.eventMap:
#          defaultEventType: com.softwareag.scike.state.StateEvent
          allowMissing: true
      - classifierCodec:
          rules:
            - com.softwareag.scike.state.StateEvent:
      - JSONCodec
      - MQTTreliableTransport
#         channel:
#           prefix: "state:"



#      - apama.eventMap
#      - myCodec:
#           doTheRightThing: true
#      - transportForAProtocol:
#           host: aprotocol.example.com
#           port: 80
